"""Added request

Revision ID: 2cb8b297be66
Revises: 06011cc68a52
Create Date: 2024-11-05 21:41:05.828024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb8b297be66'
down_revision: Union[str, None] = '06011cc68a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('ISBN', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ISBN')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
