"""updated issues table

Revision ID: 7167e0e8cb99
Revises: 2b671323187b
Create Date: 2024-10-28 17:32:19.799110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7167e0e8cb99'
down_revision: Union[str, None] = '2b671323187b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('book_id', sa.Integer(), nullable=False))
    op.drop_constraint('issue_student_id_fkey', 'issue', type_='foreignkey')
    op.create_foreign_key(None, 'issue', 'books', ['book_id'], ['book_code'], ondelete='CASCADE')
    op.create_foreign_key(None, 'issue', 'students', ['student_id'], ['id_no'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.create_foreign_key('issue_student_id_fkey', 'issue', 'books', ['student_id'], ['book_code'], ondelete='CASCADE')
    op.drop_column('issue', 'book_id')
    # ### end Alembic commands ###
