"""issue student_id primnay key

Revision ID: a30236c70651
Revises: 7167e0e8cb99
Create Date: 2024-10-28 17:35:58.535421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30236c70651'
down_revision: Union[str, None] = '7167e0e8cb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), server_default=sa.text("now() + interval '3 months'"), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue')
    # ### end Alembic commands ###
